services:
  postgres:
    image: postgres
    volumes:
      - ../create.sql:/docker-entrypoint-initdb.d/create.sql
    environment:
      POSTGRES_PASSWORD: "cccat15_1"
    ports:
      - "5432:5432"